apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-from-git
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sample-app-from-git
  template:
    metadata:
      labels:
        app: sample-app-from-git
    spec:
      containers:
      - command:
        - /app/sample-app
        image: gitopsbook/sample-app:v0.1
        name: sample-app-from-git
        ports:
        - containerPort: 8080
